### ISSUE TITLE
"You should not use this as a substitute for an actual GraphQL server for accessing a remote backend."

### ISSUE THREAD

**Issue by zuhair-naqvi** [relay-tools/relay-local-schema#11]
This this because the client would be making N requests rather than the server?

**Comment by taion** [comment]
Right, you lose all the benefits of request aggregation you'd get with a GraphQL server.

**Comment by zuhair-naqvi** [comment]
That's true. However in case of React Native, if you use the schema with the app and back it by https://github.com/facebook/dataloader (persist cache to disk) you could potentially deliver an offline first experience.. I'd be keen to hear your thoughts on this

**Comment by taion** [comment]
It's not the same because you're still resolving waterfalled loads locally rather than remotely, and end up with multiple WAN round-trips rather than data-center-internal round-trips.

**Comment by josephsavona** [comment]
This seems like a reasonable warning to have to encourage most people to use a GraphQL server, but @zuhair-naqvi's approach is interesting and totally worth exploring. You're both right! :-)

**Comment by taion** [comment]
It still seems less than ideal to use data loader from the client-side, though - you still end up with waterfalled requests, no?

**Comment by josephsavona** [comment]
@taion context is https://github.com/facebook/relay/issues/676#issuecomment-165957453
