### ISSUE TITLE
error if you're not using babel-plugin-transform-regenerator

### ISSUE THREAD

**Issue by mattecapu** [relay-tools/relay-local-schema#25]
This probably would be fixed by using transform-runtime.
Also it would be great to have an ES2015 version of the package (like `react-router/es6`) to better integrate it into existing Babel/Rollup pipelines and run better on Node v5/6 as they're now almost ES2015 compliant.

**Comment by taion** [comment]
I'd rather we take out the use of async/await here and just use promises. It's not really worth pulling in the regenerator runtime for this, and babel-runtime has its own issues.

Given that this library only has a single export, the benefits from tree-shaking are going to be nearly negligible. An ES module build like for React Router (which I set up) is the same as the normal build, with only the change to the module system. It's not going to use other ES2015 functionality.

**Comment by taion** [comment]
Fixed by https://github.com/relay-tools/relay-local-schema/pull/29.

**Comment by taion** [comment]
Released as v0.5.4.
