### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'getSource' of undefined

### ISSUE THREAD

**Issue by vetm73** [relay-tools/relay-local-schema#41]
Hi,

I get  Uncaught (in promise) TypeError: Cannot read property 'getSource' of undefined RelayPublishQueue.js:152 in case of a mutation. I get in the resolve function of the mutation but not sure where the error comes from.

Kind regards,

Mike

**Comment by taion** [comment]
you set up your relay environment wrong; follow the docs here. this has nothing to do with this lib
